2023-02-09T19:10:39.348825-0300 | INFO | App started | main.py:16
2023-02-09T19:14:54.373367-0300 | INFO | App started | main.py:16
2023-02-09T19:15:06.174071-0300 | INFO | App started | main.py:16
2023-02-09T21:54:04.288578-0300 | INFO | App started | main.py:18
2023-02-09T22:14:55.763589-0300 | ERROR | Database credentials not found in config file | models.py:43
2023-02-09T22:15:35.203040-0300 | DEBUG | Main database URI set | models.py:27
2023-02-09T22:15:35.203040-0300 | ERROR | Database credentials not found in config file | models.py:43
2023-02-09T22:15:54.355244-0300 | DEBUG | Main database URI set | models.py:27
2023-02-09T22:15:54.356315-0300 | ERROR | Database credentials not found in config file | models.py:43
2023-02-09T22:16:03.242676-0300 | DEBUG | Main database URI set | models.py:27
2023-02-09T22:16:03.242676-0300 | DEBUG | Mock database URI configured | models.py:36
2023-02-09T22:19:34.234962-0300 | DEBUG | Main Database URI set | models.py:24
2023-02-09T22:19:34.234962-0300 | DEBUG | Mock database URI set | models.py:31
2023-02-09T22:19:54.086875-0300 | DEBUG | Main Database URI set | models.py:23
2023-02-09T22:19:54.087876-0300 | DEBUG | Mock database URI set | models.py:30
2023-02-09T22:19:54.188873-0300 | INFO | App started | main.py:18
2023-02-09T22:29:17.178512-0300 | DEBUG | Main Database URI set | models.py:23
2023-02-09T22:29:17.179512-0300 | DEBUG | Mock database URI set | models.py:30
2023-02-09T22:29:17.264512-0300 | INFO | App started | main.py:18
2023-02-09T22:29:34.818571-0300 | DEBUG | Main Database URI set | models.py:23
2023-02-09T22:29:34.819572-0300 | DEBUG | Mock database URI set | models.py:30
2023-02-09T22:29:34.917571-0300 | INFO | App started | main.py:18
2023-02-09T22:29:46.221573-0300 | DEBUG | Main Database URI set | models.py:23
2023-02-09T22:29:46.221573-0300 | DEBUG | Mock database URI set | models.py:30
2023-02-09T22:58:34.341646-0300 | ERROR | Error while trying to get the main database credentials: 'DATABASE' | models.py:31
2023-02-09T22:59:57.583456-0300 | INFO | Connected in localhost with app testing status =False | models.py:39
2023-02-09T22:59:57.583456-0300 | INFO | App started | main.py:18
2023-02-09T23:04:48.944231-0300 | INFO | Connected in alpha_store with app testing status =False | models.py:40
2023-02-09T23:04:48.945232-0300 | DEBUG | Database Info: <Section: DATABASE> | models.py:41
2023-02-09T23:04:48.945232-0300 | INFO | App started | main.py:18
2023-02-09T23:05:04.974366-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:40
2023-02-09T23:05:04.975366-0300 | DEBUG | Database Info: <Section: DATABASE> | models.py:41
2023-02-09T23:05:04.975366-0300 | INFO | App started | main.py:18
2023-02-10T03:07:30.819689-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:45
2023-02-10T03:07:30.820691-0300 | INFO | Auth models configured | models.py:51
2023-02-10T03:07:30.821692-0300 | INFO | App started | main.py:18
2023-02-10T03:09:19.355117-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:45
2023-02-10T03:09:19.356117-0300 | INFO | Auth models configured | models.py:51
2023-02-10T03:09:19.358118-0300 | INFO | Auth configured | views.py:11
2023-02-10T03:09:19.358118-0300 | INFO | App started | main.py:22
2023-02-10T03:09:59.190551-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:45
2023-02-10T03:09:59.191547-0300 | INFO | Auth models configured | models.py:51
2023-02-10T03:09:59.193551-0300 | INFO | Auth configured | views.py:11
2023-02-10T03:09:59.193551-0300 | INFO | App started | main.py:22
2023-02-10T03:10:45.518537-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:45
2023-02-10T03:10:45.518537-0300 | INFO | Auth models configured | models.py:51
2023-02-10T03:10:45.519508-0300 | INFO | Auth configured | views.py:11
2023-02-10T03:10:45.520540-0300 | INFO | App started | main.py:22
2023-02-10T03:12:32.866756-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:45
2023-02-10T03:12:32.867758-0300 | INFO | Auth models configured | models.py:51
2023-02-10T03:12:32.872758-0300 | INFO | Auth configured | views.py:11
2023-02-10T03:12:32.882758-0300 | INFO | App started | main.py:22
2023-02-10T03:15:09.839832-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:45
2023-02-10T03:15:09.840836-0300 | INFO | Auth models configured | models.py:51
2023-02-10T03:15:09.843837-0300 | INFO | Auth configured | views.py:9
2023-02-10T03:15:09.844839-0300 | INFO | App started | main.py:23
2023-02-10T03:15:11.538374-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:45
2023-02-10T03:15:11.539376-0300 | INFO | Auth models configured | models.py:51
2023-02-10T03:15:11.543373-0300 | INFO | Auth configured | views.py:9
2023-02-10T03:15:11.544373-0300 | INFO | App started | main.py:23
2023-02-10T04:11:39.421071-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:46
2023-02-10T04:11:39.422069-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:47
2023-02-10T04:11:39.422069-0300 | INFO | Auth models configured | models.py:54
2023-02-10T04:11:39.423070-0300 | INFO | Auth configured | views.py:10
2023-02-10T04:11:39.423070-0300 | INFO | App started | main.py:28
2023-02-10T04:12:53.519455-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:46
2023-02-10T04:12:53.519455-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:47
2023-02-10T04:12:53.519455-0300 | INFO | Auth models configured | models.py:54
2023-02-10T04:12:53.520457-0300 | INFO | Auth configured | views.py:10
2023-02-10T04:12:53.521457-0300 | INFO | App started | main.py:28
2023-02-10T04:13:03.758289-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:46
2023-02-10T04:13:03.759289-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:47
2023-02-10T04:13:03.759289-0300 | INFO | Auth models configured | models.py:54
2023-02-10T04:13:03.760291-0300 | INFO | Auth configured | views.py:10
2023-02-10T04:13:03.761292-0300 | INFO | App started | main.py:28
2023-02-10T04:15:00.742606-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:46
2023-02-10T04:15:00.780604-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:47
2023-02-10T04:15:00.781607-0300 | INFO | Auth models configured | models.py:54
2023-02-10T04:15:00.783605-0300 | INFO | Auth configured | views.py:10
2023-02-10T04:15:00.784606-0300 | INFO | App started | main.py:28
2023-02-11T03:50:01.682027-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:46
2023-02-11T03:50:01.682027-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:47
2023-02-11T03:50:01.682997-0300 | INFO | Auth models configured | models.py:54
2023-02-11T03:50:01.685115-0300 | INFO | Auth configured | views.py:12
2023-02-11T03:50:01.685115-0300 | INFO | App started | main.py:31
2023-02-11T03:51:14.648494-0300 | DEBUG | User valid created successfully | views.py:39
2023-02-11T04:00:13.429249-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:46
2023-02-11T04:00:13.429249-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:47
2023-02-11T04:00:13.430251-0300 | INFO | Auth models configured | models.py:54
2023-02-11T04:00:13.433248-0300 | INFO | Auth configured | views.py:11
2023-02-11T04:00:13.434254-0300 | INFO | App started | main.py:31
2023-02-11T04:04:00.990635-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:46
2023-02-11T04:04:00.990635-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:47
2023-02-11T04:04:00.990635-0300 | INFO | Auth models configured | models.py:54
2023-02-11T04:04:00.996642-0300 | INFO | Auth configured | views.py:11
2023-02-11T04:04:00.996642-0300 | INFO | App started | main.py:31
2023-02-11T04:04:03.744207-0300 | ERROR | Exception on /apis/v1/auth/register [POST] | app.py:1741
2023-02-11T04:04:30.733021-0300 | ERROR | Exception on /apis/v1/auth/register [POST] | app.py:1741
2023-02-11T04:04:49.708882-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:46
2023-02-11T04:04:49.708882-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:47
2023-02-11T04:04:49.709886-0300 | INFO | Auth models configured | models.py:54
2023-02-11T04:04:49.711913-0300 | INFO | Auth configured | views.py:11
2023-02-11T04:04:49.712911-0300 | INFO | App started | main.py:31
2023-02-11T04:05:24.331403-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:46
2023-02-11T04:05:24.331403-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:47
2023-02-11T04:05:24.332404-0300 | INFO | Auth models configured | models.py:54
2023-02-11T04:05:24.336404-0300 | INFO | Auth configured | views.py:11
2023-02-11T04:05:24.336404-0300 | INFO | App started | main.py:31
2023-02-11T04:05:44.054863-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:46
2023-02-11T04:05:44.055860-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:47
2023-02-11T04:05:44.055860-0300 | INFO | Auth models configured | models.py:54
2023-02-11T04:05:44.061859-0300 | INFO | Auth configured | views.py:11
2023-02-11T04:05:44.062859-0300 | INFO | App started | main.py:31
2023-02-11T04:54:10.357890-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T04:54:10.358891-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:48
2023-02-11T04:54:10.358891-0300 | INFO | Auth models configured | models.py:55
2023-02-11T04:54:10.360891-0300 | INFO | Auth configured | views.py:11
2023-02-11T04:54:10.361891-0300 | INFO | App started | main.py:31
2023-02-11T04:54:18.762257-0300 | DEBUG | User valid created successfully | views.py:39
2023-02-11T05:39:17.172691-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:39:17.172691-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:39:17.172691-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:39:17.175691-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:39:17.175691-0300 | INFO | App started | main.py:31
2023-02-11T05:42:35.368121-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:42:35.368121-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:42:35.369124-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:42:35.373124-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:42:35.373124-0300 | INFO | App started | main.py:29
2023-02-11T05:43:14.066124-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:43:14.099124-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:43:14.119125-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:43:14.152125-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:43:14.171130-0300 | INFO | App started | main.py:29
2023-02-11T05:44:56.450009-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:44:56.450009-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:44:56.450009-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:44:56.452008-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:44:56.452979-0300 | INFO | App started | main.py:29
2023-02-11T05:45:30.787230-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:45:30.788229-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:45:30.788229-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:45:30.790228-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:45:30.790228-0300 | INFO | App started | main.py:33
2023-02-11T05:45:34.548259-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:45:34.548259-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:45:34.549230-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:45:34.550229-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:45:34.551259-0300 | INFO | App started | main.py:33
2023-02-11T05:50:13.564646-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:50:13.574644-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:50:13.578647-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:50:13.590646-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:50:13.592645-0300 | INFO | App started | main.py:33
2023-02-11T05:50:19.954646-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:50:19.974645-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:50:19.982646-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:50:19.997645-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:50:20.000646-0300 | INFO | App started | main.py:33
2023-02-11T05:50:26.363645-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:50:26.364643-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:50:26.365658-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:50:26.383643-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:50:26.385648-0300 | INFO | App started | main.py:34
2023-02-11T05:50:36.376643-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:50:36.378643-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:50:36.381647-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:50:36.387645-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:50:36.388648-0300 | INFO | App started | main.py:34
2023-02-11T05:50:52.318644-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T05:50:52.319644-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T05:50:52.320644-0300 | INFO | Auth models configured | models.py:56
2023-02-11T05:50:52.327646-0300 | INFO | Auth configured | views.py:11
2023-02-11T05:50:52.330646-0300 | INFO | App started | main.py:34
2023-02-11T06:01:32.718655-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:01:32.719655-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:01:32.719655-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:01:32.722656-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:01:32.722656-0300 | INFO | App started | <string>:28
2023-02-11T06:01:33.598682-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:01:33.598682-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:01:33.599652-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:01:33.601655-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:01:33.601655-0300 | INFO | App started | <string>:28
2023-02-11T06:05:43.812648-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:05:43.813643-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:05:43.813643-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:05:43.817646-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:05:43.817646-0300 | INFO | App started | main.py:28
2023-02-11T06:05:44.693642-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:05:44.693642-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:05:44.694642-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:05:44.697645-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:05:44.698643-0300 | INFO | App started | main.py:28
2023-02-11T06:06:40.043349-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:06:40.044350-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:06:40.045350-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:06:40.048348-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:06:40.049349-0300 | INFO | App started | main.py:28
2023-02-11T06:06:40.840350-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:06:40.841349-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:06:40.841349-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:06:40.845349-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:06:40.846346-0300 | INFO | App started | main.py:28
2023-02-11T06:06:55.915348-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:06:55.917349-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:06:55.919348-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:06:55.932350-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:06:55.936349-0300 | INFO | App started | main.py:28
2023-02-11T06:06:59.365344-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:06:59.366344-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:06:59.367346-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:06:59.370346-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:06:59.371347-0300 | INFO | App started | main.py:28
2023-02-11T06:07:01.822346-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:07:01.822346-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:07:01.823346-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:07:01.826343-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:07:01.826343-0300 | INFO | App started | main.py:28
2023-02-11T06:07:13.501632-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:07:13.501632-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:07:13.502628-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:07:13.505632-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:07:13.506628-0300 | INFO | App started | main.py:28
2023-02-11T06:07:18.973627-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:07:18.974632-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:07:18.975631-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:07:18.979630-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:07:18.980630-0300 | INFO | App started | main.py:28
2023-02-11T06:07:21.832635-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:07:21.833629-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:07:21.833629-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:07:21.837633-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:07:21.837633-0300 | INFO | App started | main.py:28
2023-02-11T06:07:29.164663-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:07:29.165662-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:07:29.165662-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:07:29.169667-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:07:29.169667-0300 | INFO | App started | main.py:28
2023-02-11T06:07:33.367664-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:07:33.368666-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:07:33.368666-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:07:33.370665-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:07:33.370665-0300 | INFO | App started | main.py:28
2023-02-11T06:07:40.747973-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:07:40.748975-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:07:40.749967-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:07:40.752967-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:07:40.753968-0300 | INFO | App started | main.py:28
2023-02-11T06:17:55.960538-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:17:55.960538-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:17:55.961542-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:17:55.963538-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:17:55.963538-0300 | INFO | App started | main.py:30
2023-02-11T06:18:31.905939-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:18:31.905939-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:18:31.906941-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:18:31.908943-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:18:31.908943-0300 | INFO | App started | main.py:30
2023-02-11T06:24:27.682338-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:24:27.683336-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:24:27.683336-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:24:27.685332-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:24:27.685332-0300 | INFO | App started | main.py:30
2023-02-11T06:24:49.769928-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:24:49.770928-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:24:49.770928-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:24:49.772927-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:24:49.772927-0300 | INFO | App started | main.py:30
2023-02-11T06:25:29.044006-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:25:29.045003-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:25:29.045003-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:25:29.048002-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:25:29.049003-0300 | INFO | App started | main.py:30
2023-02-11T06:25:34.110933-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:25:34.110933-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:25:34.111948-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:25:34.113929-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:25:34.113929-0300 | INFO | App started | main.py:30
2023-02-11T06:25:34.923930-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:25:34.924929-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:25:34.924929-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:25:34.927931-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:25:34.928933-0300 | INFO | App started | main.py:30
2023-02-11T06:26:03.548283-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:26:03.549283-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:26:03.549283-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:26:03.551282-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:26:03.551282-0300 | INFO | App started | main.py:30
2023-02-11T06:26:13.251263-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:48
2023-02-11T06:26:13.251263-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T06:26:13.252265-0300 | INFO | Auth models configured | models.py:56
2023-02-11T06:26:13.253294-0300 | INFO | Auth configured | views.py:11
2023-02-11T06:26:13.254297-0300 | INFO | App started | main.py:30
2023-02-11T13:30:19.664526-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:30:19.665525-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:30:19.665525-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:30:19.667525-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:30:19.669526-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:30:19.669526-0300 | INFO | App started | main.py:32
2023-02-11T13:41:35.269886-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:41:35.270885-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:41:35.270885-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:41:35.272885-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:41:35.274888-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:41:35.274888-0300 | INFO | App started | main.py:32
2023-02-11T13:42:00.981732-0300 | ERROR | Exception on /apis/v1/catalog/get_products [GET] | app.py:1741
2023-02-11T13:42:10.632491-0300 | ERROR | Exception on /apis/v1/catalog/get_products [GET] | app.py:1741
2023-02-11T13:42:26.874909-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:42:26.875908-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:42:26.875908-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:42:26.877911-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:42:26.879912-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:42:26.879912-0300 | INFO | App started | main.py:32
2023-02-11T13:42:27.946909-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:42:27.946909-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:42:27.947909-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:42:27.949908-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:42:27.951909-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:42:27.952910-0300 | INFO | App started | main.py:32
2023-02-11T13:43:10.220516-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:43:10.221516-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:43:10.221516-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:43:10.224515-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:43:10.227512-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:43:10.228512-0300 | INFO | App started | main.py:32
2023-02-11T13:46:27.529854-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:46:27.530854-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:46:27.530854-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:46:27.532881-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:46:27.536882-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:46:27.536882-0300 | INFO | App started | main.py:32
2023-02-11T13:47:31.409386-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:47:31.410383-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:47:31.410383-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:47:31.414381-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:47:31.417390-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:47:31.417390-0300 | INFO | App started | main.py:32
2023-02-11T13:47:35.595960-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:47:35.595960-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:47:35.596962-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:47:35.599962-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:47:35.603960-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:47:35.604963-0300 | INFO | App started | main.py:32
2023-02-11T13:47:40.591157-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:47:40.592158-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:47:40.593161-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:47:40.598159-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:47:40.604161-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:47:40.608161-0300 | INFO | App started | main.py:32
2023-02-11T13:47:44.130159-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:47:44.130159-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:47:44.131162-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:47:44.136165-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:47:44.142161-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:47:44.143163-0300 | INFO | App started | main.py:32
2023-02-11T13:47:50.353159-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:47:50.358161-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:47:50.359161-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:47:50.368161-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:47:50.374160-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:47:50.375161-0300 | INFO | App started | main.py:32
2023-02-11T13:47:55.793160-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:47:55.806163-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:47:55.807184-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:47:55.811160-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:47:55.823158-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:47:55.826162-0300 | INFO | App started | main.py:32
2023-02-11T13:48:14.557162-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:48:14.588161-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:48:14.593165-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:48:14.606159-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:48:14.639164-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:48:14.655161-0300 | INFO | App started | main.py:32
2023-02-11T13:48:30.402161-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:48:30.422161-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:48:30.439161-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:48:30.450161-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:48:30.461161-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:48:30.489163-0300 | INFO | App started | main.py:32
2023-02-11T13:48:35.121162-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:48:35.124161-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:48:35.125164-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:48:35.132166-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:48:35.139159-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:48:35.141162-0300 | INFO | App started | main.py:32
2023-02-11T13:49:11.866205-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:49:11.867201-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:49:11.867201-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:49:11.869201-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:49:11.873204-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:49:11.874208-0300 | INFO | App started | main.py:32
2023-02-11T13:49:15.777211-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:49:15.780208-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:49:15.781206-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:49:15.788208-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:49:15.804208-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:49:15.805209-0300 | INFO | App started | main.py:32
2023-02-11T13:49:28.155204-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:49:28.155204-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:49:28.158206-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:49:28.172205-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:49:28.185204-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:49:28.191205-0300 | INFO | App started | main.py:32
2023-02-11T13:50:15.249127-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:50:15.249127-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:50:15.250127-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:50:15.252130-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:50:15.256128-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:50:15.257132-0300 | INFO | App started | main.py:32
2023-02-11T13:50:35.813127-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:50:35.814131-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:50:35.814131-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:50:35.816131-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:50:35.818129-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:50:35.819129-0300 | INFO | App started | main.py:32
2023-02-11T13:50:37.182128-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:50:37.182128-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:50:37.183128-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:50:37.186128-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:50:37.189126-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:50:37.190129-0300 | INFO | App started | main.py:32
2023-02-11T13:51:12.540003-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:51:12.540974-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:51:12.540974-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:51:12.542974-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:51:12.545972-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:51:12.545972-0300 | INFO | App started | main.py:32
2023-02-11T13:51:13.805972-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:51:13.806974-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:51:13.806974-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:51:13.809971-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:51:13.812978-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:51:13.813975-0300 | INFO | App started | main.py:32
2023-02-11T13:51:47.748235-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:51:47.748235-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:51:47.749237-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:51:47.751235-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:51:47.754240-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:51:47.755241-0300 | INFO | App started | main.py:32
2023-02-11T13:52:19.740178-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:52:19.741184-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:52:19.741184-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:52:19.744175-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:52:19.749177-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:52:19.750180-0300 | INFO | App started | main.py:32
2023-02-11T13:53:02.075094-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:53:02.076095-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:53:02.076095-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:53:02.078094-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:53:02.080096-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:53:02.080096-0300 | INFO | App started | main.py:32
2023-02-11T13:53:03.472129-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:53:03.473125-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:53:03.473125-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:53:03.476098-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:53:03.478125-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:53:03.479131-0300 | INFO | App started | main.py:32
2023-02-11T13:53:25.894878-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T13:53:25.895848-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T13:53:25.895848-0300 | INFO | Auth models configured | models.py:56
2023-02-11T13:53:25.897848-0300 | INFO | Auth configured | views.py:13
2023-02-11T13:53:25.900851-0300 | INFO | Catalog configured | views.py:11
2023-02-11T13:53:25.900851-0300 | INFO | App started | main.py:32
2023-02-11T14:29:22.204226-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T14:29:22.204226-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T14:29:22.205227-0300 | INFO | Auth models configured | models.py:56
2023-02-11T14:29:22.208229-0300 | INFO | Auth configured | views.py:13
2023-02-11T14:29:22.211226-0300 | INFO | Catalog configured | views.py:11
2023-02-11T14:29:22.212225-0300 | INFO | App started | main.py:32
2023-02-11T14:29:29.255226-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T14:29:29.256227-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T14:29:29.257226-0300 | INFO | Auth models configured | models.py:56
2023-02-11T14:29:29.259229-0300 | INFO | Auth configured | views.py:13
2023-02-11T14:29:29.263225-0300 | INFO | Catalog configured | views.py:11
2023-02-11T14:29:29.263225-0300 | INFO | App started | main.py:32
2023-02-11T14:29:44.029224-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T14:29:44.030224-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T14:29:44.030224-0300 | INFO | Auth models configured | models.py:56
2023-02-11T14:29:44.033225-0300 | INFO | Auth configured | views.py:13
2023-02-11T14:29:44.036226-0300 | INFO | Catalog configured | views.py:11
2023-02-11T14:29:44.036226-0300 | INFO | App started | main.py:32
2023-02-11T14:29:49.264226-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T14:29:49.265227-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T14:29:49.265227-0300 | INFO | Auth models configured | models.py:56
2023-02-11T14:29:49.267226-0300 | INFO | Auth configured | views.py:13
2023-02-11T14:29:49.271227-0300 | INFO | Catalog configured | views.py:11
2023-02-11T14:29:49.272227-0300 | INFO | App started | main.py:32
2023-02-11T14:33:45.657086-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T14:33:45.658086-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T14:33:45.658086-0300 | INFO | Auth models configured | models.py:56
2023-02-11T14:33:45.662087-0300 | INFO | Auth configured | views.py:13
2023-02-11T14:33:45.666085-0300 | INFO | Catalog configured | views.py:11
2023-02-11T14:33:45.666085-0300 | INFO | App started | main.py:32
2023-02-11T14:33:47.432085-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T14:33:47.435088-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T14:33:47.437088-0300 | INFO | Auth models configured | models.py:56
2023-02-11T14:33:47.442084-0300 | INFO | Auth configured | views.py:13
2023-02-11T14:33:47.447085-0300 | INFO | Catalog configured | views.py:11
2023-02-11T14:33:47.449089-0300 | INFO | App started | main.py:32
2023-02-11T14:35:41.686907-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T14:35:41.687907-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T14:35:41.687907-0300 | INFO | Auth models configured | models.py:56
2023-02-11T14:35:41.689910-0300 | INFO | Auth configured | views.py:13
2023-02-11T14:35:41.695913-0300 | INFO | Catalog configured | views.py:11
2023-02-11T14:35:41.696909-0300 | INFO | App started | main.py:32
2023-02-11T14:36:14.191886-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T14:36:14.192887-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T14:36:14.192887-0300 | INFO | Auth models configured | models.py:56
2023-02-11T14:36:14.194886-0300 | INFO | Auth configured | views.py:13
2023-02-11T14:36:14.196888-0300 | INFO | Catalog configured | views.py:11
2023-02-11T14:36:14.197886-0300 | INFO | App started | main.py:32
2023-02-11T14:36:52.165165-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T14:36:52.165165-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T14:36:52.166135-0300 | INFO | Auth models configured | models.py:56
2023-02-11T14:36:52.168137-0300 | INFO | Auth configured | views.py:13
2023-02-11T14:36:52.171134-0300 | INFO | Catalog configured | views.py:11
2023-02-11T14:36:52.171134-0300 | INFO | App started | main.py:32
2023-02-11T14:36:54.899925-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T14:36:54.899925-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T14:36:54.899925-0300 | INFO | Auth models configured | models.py:56
2023-02-11T14:36:54.903930-0300 | INFO | Auth configured | views.py:13
2023-02-11T14:36:54.906925-0300 | INFO | Catalog configured | views.py:11
2023-02-11T14:36:54.907924-0300 | INFO | App started | main.py:32
2023-02-11T15:24:31.870355-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T15:24:31.870355-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T15:24:31.871356-0300 | INFO | Auth models configured | models.py:56
2023-02-11T15:24:31.872354-0300 | INFO | Auth configured | views.py:13
2023-02-11T15:24:31.875355-0300 | INFO | Catalog configured | views.py:12
2023-02-11T15:24:31.875355-0300 | INFO | App started | main.py:32
2023-02-11T15:26:49.750971-0300 | INFO | Connected in alpha_store with app testing status: False | models.py:47
2023-02-11T15:26:49.750971-0300 | DEBUG | Database URI: <SQLAlchemy>, postgresql+pg8000://postgres:123@localhost/alpha_store | models.py:49
2023-02-11T15:26:49.750971-0300 | INFO | Auth models configured | models.py:56
2023-02-11T15:26:49.752972-0300 | INFO | Auth configured | views.py:13
2023-02-11T15:26:49.756972-0300 | INFO | Catalog configured | views.py:12
2023-02-11T15:26:49.756972-0300 | INFO | App started | main.py:32
